/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

/**
 *
 * @author ellenportugues
 */
public class AdminInformation extends javax.swing.JFrame {

    /**
     * Creates new form AdminInformation
     */
    public AdminInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ljValkommen = new javax.swing.JLabel();
        btnAndraLosenord = new javax.swing.JButton();
        btnRegistrera = new javax.swing.JButton();
        btnListor = new javax.swing.JButton();
        btnSokAgentInformation = new javax.swing.JButton();
        btnAndraAgentInformation = new javax.swing.JButton();
        btnTaBortAlien = new javax.swing.JButton();
        btnTaBortUtrustning = new javax.swing.JButton();
        btnNyregistreraAgent = new javax.swing.JButton();
        btnTaBortAgent = new javax.swing.JButton();
        btnAndraAdminstatus = new javax.swing.JButton();
        btnAndraInformationOmradeschef = new javax.swing.JButton();
        btnAndraInfromationKontorschef = new javax.swing.JButton();
        btnÄndraAlienInformation = new javax.swing.JButton();
        btnSokAgentInfo = new javax.swing.JButton();
        btnInfoOmradeschef = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ljValkommen.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        ljValkommen.setText("Välkommen!");

        btnAndraLosenord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnAndraLosenord.setText("Ändra Lösenord");
        btnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenordActionPerformed(evt);
            }
        });

        btnRegistrera.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnRegistrera.setText("Registrera");
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        btnListor.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnListor.setText("Listor");
        btnListor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListorActionPerformed(evt);
            }
        });

        btnSokAgentInformation.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnSokAgentInformation.setText("Sök Agent Information");
        btnSokAgentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokAgentInformationActionPerformed(evt);
            }
        });

        btnAndraAgentInformation.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnAndraAgentInformation.setText("Ändra agent information");
        btnAndraAgentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraAgentInformationActionPerformed(evt);
            }
        });

        btnTaBortAlien.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnTaBortAlien.setText("Ta bort alien");
        btnTaBortAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortAlienActionPerformed(evt);
            }
        });

        btnTaBortUtrustning.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnTaBortUtrustning.setText("Ta bort utrustning");
        btnTaBortUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortUtrustningActionPerformed(evt);
            }
        });

        btnNyregistreraAgent.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnNyregistreraAgent.setText("Nyregistrera agent");
        btnNyregistreraAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyregistreraAgentActionPerformed(evt);
            }
        });

        btnTaBortAgent.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnTaBortAgent.setText("Ta bort agent");
        btnTaBortAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortAgentActionPerformed(evt);
            }
        });

        btnAndraAdminstatus.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnAndraAdminstatus.setText("Ändra adminstatus");
        btnAndraAdminstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraAdminstatusActionPerformed(evt);
            }
        });

        btnAndraInformationOmradeschef.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnAndraInformationOmradeschef.setText("Ändra information områdeschef");
        btnAndraInformationOmradeschef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraInformationOmradeschefActionPerformed(evt);
            }
        });

        btnAndraInfromationKontorschef.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnAndraInfromationKontorschef.setText("Ändra information kontorschef");
        btnAndraInfromationKontorschef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraInfromationKontorschefActionPerformed(evt);
            }
        });

        btnÄndraAlienInformation.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnÄndraAlienInformation.setText("Ändra alien information");
        btnÄndraAlienInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraAlienInformationActionPerformed(evt);
            }
        });

        btnSokAgentInfo.setText("Sök info om alien");
        btnSokAgentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokAgentInfoActionPerformed(evt);
            }
        });

        btnInfoOmradeschef.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnInfoOmradeschef.setText("Sök info om områdeschef");
        btnInfoOmradeschef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoOmradeschefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ljValkommen)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAndraLosenord)
                            .addComponent(btnRegistrera)
                            .addComponent(btnListor)
                            .addComponent(btnSokAgentInformation)
                            .addComponent(btnTaBortAlien)
                            .addComponent(btnSokAgentInfo)
                            .addComponent(btnTaBortUtrustning)
                            .addComponent(btnTaBortAgent))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNyregistreraAgent)
                            .addComponent(btnAndraAdminstatus)
                            .addComponent(btnAndraAgentInformation)
                            .addComponent(btnAndraInformationOmradeschef)
                            .addComponent(btnAndraInfromationKontorschef)
                            .addComponent(btnÄndraAlienInformation)
                            .addComponent(btnInfoOmradeschef))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ljValkommen)
                .addGap(12, 12, 12)
                .addComponent(btnInfoOmradeschef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndraLosenord)
                    .addComponent(btnAndraAgentInformation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrera)
                    .addComponent(btnNyregistreraAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListor)
                    .addComponent(btnAndraAdminstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSokAgentInformation)
                    .addComponent(btnAndraInformationOmradeschef))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndraInfromationKontorschef)
                    .addComponent(btnSokAgentInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnÄndraAlienInformation)
                    .addComponent(btnTaBortAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(btnTaBortUtrustning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaBortAgent)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenordActionPerformed
    new AgentÄndraLösenord().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnAndraLosenordActionPerformed

    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
    new AgentRegistrera().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnRegistreraActionPerformed

    private void btnListorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListorActionPerformed
    new AgentLista().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnListorActionPerformed

    private void btnSokAgentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokAgentInformationActionPerformed
    new AgentSok().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnSokAgentInformationActionPerformed

    private void btnAndraAgentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraAgentInformationActionPerformed
    new AgentÄndraInformationOmAgent().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnAndraAgentInformationActionPerformed

    private void btnTaBortAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortAlienActionPerformed
    new AdminTaBortAlien().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnTaBortAlienActionPerformed

    private void btnTaBortUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortUtrustningActionPerformed
    new AdminTaBortUtrustning().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnTaBortUtrustningActionPerformed

    private void btnTaBortAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortAgentActionPerformed
    new AdminTaBortAgent().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnTaBortAgentActionPerformed

    private void btnNyregistreraAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyregistreraAgentActionPerformed
    new AdminNyregistreraAgent().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnNyregistreraAgentActionPerformed

    private void btnAndraAdminstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraAdminstatusActionPerformed
    new AdminÄndraAdminstatus().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnAndraAdminstatusActionPerformed

    private void btnAndraInformationOmradeschefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraInformationOmradeschefActionPerformed
    new AdminÄndraInformationOmrådeschef().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnAndraInformationOmradeschefActionPerformed

    private void btnAndraInfromationKontorschefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraInfromationKontorschefActionPerformed
    new AdminÄndraInformationKontorschef().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnAndraInfromationKontorschefActionPerformed

    private void btnÄndraAlienInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraAlienInformationActionPerformed
    new AgentÄndraInformationOmAlien().setVisible(rootPaneCheckingEnabled); 
    }//GEN-LAST:event_btnÄndraAlienInformationActionPerformed

    private void btnSokAgentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokAgentInfoActionPerformed
        new AgentSökInformationOmAlien().setVisible(rootPaneCheckingEnabled); 
    }//GEN-LAST:event_btnSokAgentInfoActionPerformed

    private void btnInfoOmradeschefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoOmradeschefActionPerformed
        new AgentVisaInformationOmOmrådeschef().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnInfoOmradeschefActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraAdminstatus;
    private javax.swing.JButton btnAndraAgentInformation;
    private javax.swing.JButton btnAndraInformationOmradeschef;
    private javax.swing.JButton btnAndraInfromationKontorschef;
    private javax.swing.JButton btnAndraLosenord;
    private javax.swing.JToggleButton btnInfoOmradeschef;
    private javax.swing.JButton btnListor;
    private javax.swing.JButton btnNyregistreraAgent;
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JButton btnSokAgentInfo;
    private javax.swing.JButton btnSokAgentInformation;
    private javax.swing.JButton btnTaBortAgent;
    private javax.swing.JButton btnTaBortAlien;
    private javax.swing.JButton btnTaBortUtrustning;
    private javax.swing.JButton btnÄndraAlienInformation;
    private javax.swing.JLabel ljValkommen;
    // End of variables declaration//GEN-END:variables
}
