/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ellenportugues
 */
public class AdminÄndraAdminstatus extends javax.swing.JFrame {
        
    private InfDB idb;
    
    /**
     * Creates new form AdminÄndraAdminstatus
     */
    public AdminÄndraAdminstatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAndraAdminststatus = new javax.swing.JLabel();
        btnAndraAdminstatus = new javax.swing.JButton();
        jlAgentID = new javax.swing.JLabel();
        jlNyAdminstatus = new javax.swing.JLabel();
        tfAngivetAgentID = new javax.swing.JTextField();
        tfAngivenAdminstatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlAndraAdminststatus.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jlAndraAdminststatus.setText("Ändra Adminstatus");

        btnAndraAdminstatus.setText("Ändra Adminstatus");
        btnAndraAdminstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraAdminstatusActionPerformed(evt);
            }
        });

        jlAgentID.setText("Agent ID: ");

        jlNyAdminstatus.setText("Ny adminstatus J/N:");

        tfAngivetAgentID.setColumns(10);

        tfAngivenAdminstatus.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNyAdminstatus)
                    .addComponent(jlAgentID))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAngivetAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAngivenAdminstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlAndraAdminststatus)
                    .addComponent(btnAndraAdminstatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlAndraAdminststatus)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAgentID)
                    .addComponent(tfAngivetAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNyAdminstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAngivenAdminstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(btnAndraAdminstatus)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Metod för att ändra status på en agent till eller från administratör.
    private void btnAndraAdminstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraAdminstatusActionPerformed
  
              if (Validering.textFaltHarVarde(tfAngivetAgentID) || Validering.textFaltHarVarde(tfAngivenAdminstatus)){
        
             try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
          
            String aid = tfAngivetAgentID.getText();
            String admin = tfAngivenAdminstatus.getText();
            String fraga = "Select administrator from Agent where Agent_ID= '" +aid+"'";
            String svar = idb.fetchSingle(fraga);
            String resultat = svar;
            
            String fraga1 = "Update Agent set administrator= '" + admin + "' where Agent_ID= '" +aid+ "'";
            
                    
                 if ((Validering.adminStatus(resultat))  == true){
                        idb.update(fraga1);
                        
                     JOptionPane.showMessageDialog(null, "Agentens adminstatus har uppgraderats");
                    }
                 
                 else if(Validering.adminStatus(resultat) == false){
                     idb. update(fraga1);
                     
                     JOptionPane.showMessageDialog(null, "Agentens adminstatus har uppgraderats");
                     } 
                 
                    
                   else {
                    JOptionPane.showMessageDialog(null, "Agentens adminstatus kunde inte uppdateras, kontrollera dina uppgifter");
                    }
             }
          
                    catch(InfException ettUndantag){
                       JOptionPane.showMessageDialog(null, "Något gick fel!");
                       System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
            }     
            }   
         
    
    }//GEN-LAST:event_btnAndraAdminstatusActionPerformed

    
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminÄndraAdminstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminÄndraAdminstatus().setVisible(true);
            }
        });
    }
        
       
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraAdminstatus;
    private javax.swing.JLabel jlAgentID;
    private javax.swing.JLabel jlAndraAdminststatus;
    private javax.swing.JLabel jlNyAdminstatus;
    private javax.swing.JTextField tfAngivenAdminstatus;
    private javax.swing.JTextField tfAngivetAgentID;
    // End of variables declaration//GEN-END:variables
        }
