/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author flind
 */
public class AgentÄndraInformationOmAlien extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form AgentÄndraInformation
     */
    public AgentÄndraInformationOmAlien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlAndraInfo = new javax.swing.JLabel();
        jlAndraNamn = new javax.swing.JLabel();
        jlAndraTelefon = new javax.swing.JLabel();
        jlAndraPlats = new javax.swing.JLabel();
        jlAndraAnsvarigAgent = new javax.swing.JLabel();
        tfAndraNamn = new javax.swing.JTextField();
        tfAndraTelefon = new javax.swing.JTextField();
        tfAndraPlats = new javax.swing.JTextField();
        tfAndraAnsvarigAgent = new javax.swing.JTextField();
        btnNamn = new javax.swing.JButton();
        btnTelefon = new javax.swing.JButton();
        btnPlats = new javax.swing.JButton();
        btnAnsvarigAgent = new javax.swing.JButton();
        jlVemAndra = new javax.swing.JLabel();
        tfVemAndra = new javax.swing.JTextField();
        btnAndraRas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlAndraInfo.setText("Ändra information om en alien!");

        jlAndraNamn.setText("Ändra namn");

        jlAndraTelefon.setText("Ändra telefonnummer");

        jlAndraPlats.setText("Ändra plats");

        jlAndraAnsvarigAgent.setText("Ändra ansvarig agent");

        tfAndraNamn.setColumns(12);

        tfAndraTelefon.setColumns(12);

        tfAndraPlats.setColumns(12);

        tfAndraAnsvarigAgent.setColumns(12);

        btnNamn.setText("Ändra");
        btnNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamnActionPerformed(evt);
            }
        });

        btnTelefon.setText("Ändra");
        btnTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonActionPerformed(evt);
            }
        });

        btnPlats.setText("Ändra");
        btnPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlatsActionPerformed(evt);
            }
        });

        btnAnsvarigAgent.setText("Ändra");
        btnAnsvarigAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnsvarigAgentActionPerformed(evt);
            }
        });

        jlVemAndra.setText("Ange namn på alien du vill ändra:");

        tfVemAndra.setColumns(12);

        btnAndraRas.setText("Ändra ras");
        btnAndraRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraRasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jlAndraInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlAndraNamn)
                            .addComponent(jlAndraTelefon)
                            .addComponent(jlAndraPlats)
                            .addComponent(jlAndraAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAndraAnsvarigAgent)
                            .addComponent(tfAndraPlats)
                            .addComponent(tfAndraTelefon)
                            .addComponent(tfAndraNamn))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNamn)
                            .addComponent(btnTelefon)
                            .addComponent(btnPlats)
                            .addComponent(btnAnsvarigAgent)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAndraRas))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlVemAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(tfVemAndra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAndraInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlVemAndra)
                    .addComponent(tfVemAndra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAndraNamn)
                    .addComponent(tfAndraNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNamn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAndraTelefon)
                    .addComponent(tfAndraTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelefon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAndraPlats)
                    .addComponent(tfAndraPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlats))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAndraAnsvarigAgent)
                    .addComponent(tfAndraAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnsvarigAgent))
                .addGap(18, 18, 18)
                .addComponent(btnAndraRas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Metod för att ändra namn på en alien.
    private void btnNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamnActionPerformed
       if (Validering.textFaltHarVarde(tfVemAndra)){
        try{
            
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            
            String vilkenAlien = tfVemAndra.getText();
            String nyttNamn = tfAndraNamn.getText();
            
            String fraga = "update alien set namn ='" + nyttNamn + "'where namn= '" + vilkenAlien+"'";
            idb.update(fraga);
            JOptionPane.showMessageDialog(null, "Namnet är ändrat");
        }
        
        catch(InfException ettUndantag){
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
       }
    }//GEN-LAST:event_btnNamnActionPerformed

    //Metod för att ändra telefonnummer på en alien.
    private void btnTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonActionPerformed
        try{
            
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            
            String vilkenAlien = tfVemAndra.getText();
            String nyttTelefonnummer = tfAndraTelefon.getText();
            
            String fraga = "update alien set telefon ='" + nyttTelefonnummer + "'where namn= '" + vilkenAlien+"'";
            idb.update(fraga);
            JOptionPane.showMessageDialog(null, "Telefonnumret är ändrat");
        }
        
        catch(InfException ettUndantag){
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }//GEN-LAST:event_btnTelefonActionPerformed
    
    //Metod för att ändra plats på en alien.
    private void btnPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlatsActionPerformed
        try{
            
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            
            String vilkenAlien = tfVemAndra.getText();
            String nyPlats = tfAndraPlats.getText();
            
            String fraga = "update alien set plats ='" + nyPlats + "'where namn= '" + vilkenAlien+"'";
            idb.update(fraga);
            JOptionPane.showMessageDialog(null, "Platsen är ändrat");
        }
        
        catch(InfException ettUndantag){
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }//GEN-LAST:event_btnPlatsActionPerformed

    //Metod för att ändra vilken agent som är ansvarig över en alien.
    private void btnAnsvarigAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnsvarigAgentActionPerformed
        try{
            
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            
            String vilkenAlien = tfVemAndra.getText();
            String nyAnsvarigAgent = tfAndraAnsvarigAgent.getText();
            
            String fraga = "update alien set ansvarig_agent ='" + nyAnsvarigAgent + "'where namn= '" + vilkenAlien+"'";
            idb.update(fraga);
            JOptionPane.showMessageDialog(null, "Ansvarig agent är ändrat");
        }
        
        catch(InfException ettUndantag){
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }//GEN-LAST:event_btnAnsvarigAgentActionPerformed

    private void btnAndraRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraRasActionPerformed
    new AgentÄndraAlienRas().setVisible(rootPaneCheckingEnabled);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndraRasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentÄndraInformationOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentÄndraInformationOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentÄndraInformationOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentÄndraInformationOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentÄndraInformationOmAlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraRas;
    private javax.swing.JButton btnAnsvarigAgent;
    private javax.swing.JButton btnNamn;
    private javax.swing.JButton btnPlats;
    private javax.swing.JButton btnTelefon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jlAndraAnsvarigAgent;
    private javax.swing.JLabel jlAndraInfo;
    private javax.swing.JLabel jlAndraNamn;
    private javax.swing.JLabel jlAndraPlats;
    private javax.swing.JLabel jlAndraTelefon;
    private javax.swing.JLabel jlVemAndra;
    private javax.swing.JTextField tfAndraAnsvarigAgent;
    private javax.swing.JTextField tfAndraNamn;
    private javax.swing.JTextField tfAndraPlats;
    private javax.swing.JTextField tfAndraTelefon;
    private javax.swing.JTextField tfVemAndra;
    // End of variables declaration//GEN-END:variables
}
