/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author flind
 */
public class AgentListaAlienPåSpecifikPlats extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form AgentListaAlienPåSpecifikPlats
     */
    public AgentListaAlienPåSpecifikPlats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlVal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taVisa = new javax.swing.JTextArea();
        btnOrebro = new javax.swing.JButton();
        btnVasteras = new javax.swing.JButton();
        btnBoras = new javax.swing.JButton();
        btnVilhelmina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlVal.setText("Välj ett område!");

        taVisa.setColumns(20);
        taVisa.setRows(5);
        jScrollPane1.setViewportView(taVisa);

        btnOrebro.setText("Örebro");
        btnOrebro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrebroActionPerformed(evt);
            }
        });

        btnVasteras.setText("Västerås");
        btnVasteras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVasterasActionPerformed(evt);
            }
        });

        btnBoras.setText("Borås");
        btnBoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorasActionPerformed(evt);
            }
        });

        btnVilhelmina.setText("Vilhelmina");
        btnVilhelmina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVilhelminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlVal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnOrebro)
                            .addGap(18, 18, 18)
                            .addComponent(btnVasteras)
                            .addGap(18, 18, 18)
                            .addComponent(btnBoras)
                            .addGap(18, 18, 18)
                            .addComponent(btnVilhelmina))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlVal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrebro)
                    .addComponent(btnVasteras)
                    .addComponent(btnBoras)
                    .addComponent(btnVilhelmina))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVasterasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVasterasActionPerformed
        taVisa.setText("Namn" + "\n");
        
        try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            
            String vasteras = btnVasteras.getText();
            String fraga1 = "select alien.namn, plats.benamning from alien join plats on alien.plats = plats.plats_id where benamning = '"+vasteras+"'";
            ArrayList<String> allaAliens = idb.fetchColumn(fraga1);
           
           
            
            for(String alienNamn : allaAliens){
                taVisa.append(alienNamn);
                taVisa.append("\n");

        }}
        
        catch(InfException ettUndantag){
        
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }//GEN-LAST:event_btnVasterasActionPerformed

    private void btnOrebroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrebroActionPerformed
        
        taVisa.setText("Namn" + "\n");
        try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            
            String orebro = btnOrebro.getText();
            String fraga1 = "select alien.namn, plats.benamning from alien join plats on alien.plats = plats.plats_id where benamning = '"+orebro+"'";
            ArrayList<String> allaAliens = idb.fetchColumn(fraga1);
           
           
            
            for(String alienNamn : allaAliens){
                taVisa.append(alienNamn);
                taVisa.append("\n");

        }}
        
        catch(InfException ettUndantag){
        
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }//GEN-LAST:event_btnOrebroActionPerformed

    private void btnBorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorasActionPerformed
        taVisa.setText("Namn" + "\n");
        try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            
            String boras = btnBoras.getText();
            String fraga1 = "select alien.namn, plats.benamning from alien join plats on alien.plats = plats.plats_id where benamning = '"+boras+"'";
            ArrayList<String> allaAliens = idb.fetchColumn(fraga1);
           
           
            
            for(String alienNamn : allaAliens){
                taVisa.append(alienNamn);
                taVisa.append("\n");

        }}
        
        catch(InfException ettUndantag){
        
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }//GEN-LAST:event_btnBorasActionPerformed

    private void btnVilhelminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVilhelminaActionPerformed
        taVisa.setText("Namn" + "\n");
        try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            
            String vilhelmina = btnVilhelmina.getText();
            String fraga1 = "select alien.namn, plats.benamning from alien join plats on alien.plats = plats.plats_id where benamning = '"+vilhelmina+"'";
            ArrayList<String> allaAliens = idb.fetchColumn(fraga1);
           
           
            
            for(String alienNamn : allaAliens){
                taVisa.append(alienNamn);
                taVisa.append("\n");

        }}
        
        catch(InfException ettUndantag){
        
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }//GEN-LAST:event_btnVilhelminaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentListaAlienPåSpecifikPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentListaAlienPåSpecifikPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentListaAlienPåSpecifikPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentListaAlienPåSpecifikPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentListaAlienPåSpecifikPlats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoras;
    private javax.swing.JButton btnOrebro;
    private javax.swing.JButton btnVasteras;
    private javax.swing.JButton btnVilhelmina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlVal;
    private javax.swing.JTextArea taVisa;
    // End of variables declaration//GEN-END:variables
}
