/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ellenportugues
 */
public class AgentInlogg extends javax.swing.JFrame {

    private InfDB idb;
   
    /**
     * Creates new form AgentInlogg
     */
    public AgentInlogg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAgentID = new javax.swing.JLabel();
        jlAgentLösenord = new javax.swing.JLabel();
        tfAngivetAgentID = new javax.swing.JTextField();
        tfAngivetLosenord = new javax.swing.JTextField();
        btnAgentLoggaIn = new javax.swing.JButton();
        jlAgentInlogg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlAgentID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jlAgentID.setText("AgentID:");

        jlAgentLösenord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jlAgentLösenord.setText("Lösenord:");

        tfAngivetAgentID.setColumns(6);

        tfAngivetLosenord.setColumns(6);

        btnAgentLoggaIn.setText("Logga in");
        btnAgentLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgentLoggaInActionPerformed(evt);
            }
        });

        jlAgentInlogg.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jlAgentInlogg.setText("Agent Inloggning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlAgentID)
                            .addComponent(jlAgentLösenord))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfAngivetAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAngivetLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jlAgentInlogg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnAgentLoggaIn)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlAgentInlogg)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAgentID)
                    .addComponent(tfAngivetAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAgentLösenord)
                    .addComponent(tfAngivetLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnAgentLoggaIn)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Metod för att logga in som agent.
    private void btnAgentLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentLoggaInActionPerformed

         if (Validering.textFaltHarVarde(tfAngivetAgentID) || Validering.textFaltHarVarde(tfAngivetLosenord)){
            
       
        try {
           idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
         
            String aid = tfAngivetAgentID.getText();
            String losen = tfAngivetLosenord.getText();
            String fraga1 = "Select Losenord from Agent where Agent_ID= '"+aid+"'";
            String svar1 = idb.fetchSingle(fraga1);
            String resultat1 = svar1;
            
            //boolean administrator = false;
            String fraga2 = "Select Administrator from Agent where Agent_ID= '"+aid+"'";
            String svar2 = idb.fetchSingle(fraga2);
            String resultat2 = svar2;
          

            if (Validering.adminStatus(resultat2) && losen.contains(resultat1)) {
                System.out.println("Inloggad");
                 //  JOptionPane.showMessageDialog(null, "Inloggad");
                new AdminInformation().setVisible(rootPaneCheckingEnabled);
                
            }
            
            else if (!Validering.adminStatus(resultat2) && losen.contains(resultat1)) {
                 //administrator = false;
                System.out.println("Inloggad");
                //  JOptionPane.showMessageDialog(null, "Inloggad");
                 new AgentInformation().setVisible(rootPaneCheckingEnabled);
            }
            else {
                JOptionPane.showMessageDialog(null, "Kunde inte logga in, kontrollera dina upppgifter");
                
        }
        }
        
          catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }
        
 
            
    }//GEN-LAST:event_btnAgentLoggaInActionPerformed
    }
         
        /**
         * @param args the command line arguments
         */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentInlogg().setVisible(true);
            }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgentLoggaIn;
    private javax.swing.JLabel jlAgentID;
    private javax.swing.JLabel jlAgentInlogg;
    private javax.swing.JLabel jlAgentLösenord;
    private javax.swing.JTextField tfAngivetAgentID;
    private javax.swing.JTextField tfAngivetLosenord;
    // End of variables declaration//GEN-END:variables
}
