/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author flind
 */
public class AgentVisaInformationOmOmrådeschef extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form AgentVisaInformationOmOmrådeschef
     */
    public AgentVisaInformationOmOmrådeschef() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlVisaInfo = new javax.swing.JLabel();
        btnSvealand = new javax.swing.JButton();
        btnGötaland = new javax.swing.JButton();
        btnNorrland = new javax.swing.JButton();
        jlNamn = new javax.swing.JLabel();
        tfNamn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlVisaInfo.setText("Visa information om områdeschef!");

        btnSvealand.setText("Svealand");
        btnSvealand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSvealandActionPerformed(evt);
            }
        });

        btnGötaland.setText("Götaland");
        btnGötaland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGötalandActionPerformed(evt);
            }
        });

        btnNorrland.setText("Norrland");
        btnNorrland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNorrlandActionPerformed(evt);
            }
        });

        jlNamn.setText("Namn:");

        tfNamn.setColumns(12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlVisaInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSvealand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btnGötaland)
                        .addGap(54, 54, 54)
                        .addComponent(btnNorrland)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jlNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlVisaInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSvealand)
                    .addComponent(btnGötaland)
                    .addComponent(btnNorrland))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNamn)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Metod för att visa namnet på områdeschefen över Götaland.
    private void btnGötalandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGötalandActionPerformed
        try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            String omrade = btnGötaland.getText();
            
            String iDpaOmrade = "select omrades_id from omrade where benamning = '"+omrade+"'";
            String svarID = idb.fetchSingle(iDpaOmrade);
             
            String vilkenAgent = "select agent_id from omradeschef where omrade = '"+svarID+"'";
            String svarVilkenAgent = idb.fetchSingle(vilkenAgent);
                    
            String vilketNamn = "select namn from agent where agent_id = '"+svarVilkenAgent+"'";
            String svarVilketNamn = idb.fetchSingle(vilketNamn);
            
            tfNamn.setText(svarVilketNamn);
            
            
            
        }
        
        catch(InfException ettUndantag){
            JOptionPane.showMessageDialog(null, "Något gick fel!"); 
        }
    }//GEN-LAST:event_btnGötalandActionPerformed
    //Metod för att visa namnet på områdeschefen över Svealand.
    private void btnSvealandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSvealandActionPerformed
        try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            String omrade = btnSvealand.getText();
            
            String iDpaOmrade = "select omrades_id from omrade where benamning = '"+omrade+"'";
            String svarID = idb.fetchSingle(iDpaOmrade);
             
            String vilkenAgent = "select agent_id from omradeschef where omrade = '"+svarID+"'";
            String svarVilkenAgent = idb.fetchSingle(vilkenAgent);
                    
            String vilketNamn = "select namn from agent where agent_id = '"+svarVilkenAgent+"'";
            String svarVilketNamn = idb.fetchSingle(vilketNamn);
            
            tfNamn.setText(svarVilketNamn);
            
            
            
        }
        
        catch(InfException ettUndantag){
            JOptionPane.showMessageDialog(null, "Något gick fel!"); 
        }

    }//GEN-LAST:event_btnSvealandActionPerformed
    //Metod för att visa namnet på områdeschefen över Norrland.
    private void btnNorrlandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNorrlandActionPerformed
        try{
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            String omrade = btnNorrland.getText();
            
            String iDpaOmrade = "select omrades_id from omrade where benamning = '"+omrade+"'";
            String svarID = idb.fetchSingle(iDpaOmrade);
             
            String vilkenAgent = "select agent_id from omradeschef where omrade = '"+svarID+"'";
            String svarVilkenAgent = idb.fetchSingle(vilkenAgent);
                    
            String vilketNamn = "select namn from agent where agent_id = '"+svarVilkenAgent+"'";
            String svarVilketNamn = idb.fetchSingle(vilketNamn);
            
            tfNamn.setText(svarVilketNamn);
            
            
            
        }
        
        catch(InfException ettUndantag){
            JOptionPane.showMessageDialog(null, "Något gick fel!"); 
        }
    }//GEN-LAST:event_btnNorrlandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentVisaInformationOmOmrådeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentVisaInformationOmOmrådeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentVisaInformationOmOmrådeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentVisaInformationOmOmrådeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentVisaInformationOmOmrådeschef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGötaland;
    private javax.swing.JButton btnNorrland;
    private javax.swing.JButton btnSvealand;
    private javax.swing.JLabel jlNamn;
    private javax.swing.JLabel jlVisaInfo;
    private javax.swing.JTextField tfNamn;
    // End of variables declaration//GEN-END:variables
}
