/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ellenportugues
 */
public class AlienInlogg extends javax.swing.JFrame {

    private InfDB idb;
    /**
     * Creates new form AlienInlogg
     */
    public AlienInlogg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAlienInloggning = new javax.swing.JLabel();
        jlAlienID = new javax.swing.JLabel();
        jlLosenord = new javax.swing.JLabel();
        tfAngivetAlienID = new javax.swing.JTextField();
        tfAngivetAlienLosenord = new javax.swing.JTextField();
        btnAlienLoggaIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlAlienInloggning.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jlAlienInloggning.setText("Alien Inloggning");

        jlAlienID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jlAlienID.setText("AlienID:");

        jlLosenord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jlLosenord.setText("Lösenord:");

        tfAngivetAlienID.setColumns(6);

        tfAngivetAlienLosenord.setColumns(6);

        btnAlienLoggaIn.setText("Logga in");
        btnAlienLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlienLoggaInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlLosenord)
                            .addComponent(jlAlienID))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAngivetAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlAlienInloggning)
                            .addComponent(tfAngivetAlienLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnAlienLoggaIn)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlAlienInloggning)
                        .addGap(65, 65, 65)
                        .addComponent(jlAlienID))
                    .addComponent(tfAngivetAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLosenord)
                    .addComponent(tfAngivetAlienLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnAlienLoggaIn)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlienLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlienLoggaInActionPerformed
        // TODO add your handling code here:
        // koda till nästa sida, 
        
           try {
          idb = new InfDB ("mibdb", "3306", "mibdba", "mibkey");
          String anid = tfAngivetAlienID.getText();
          String losen =tfAngivetAlienLosenord.getText();
          String fraga = "Select Losenord from Alien where Alien_ID= '"+anid+"'";
          String svar = idb.fetchSingle(fraga);
          String resultat = svar;
          
        
         if(losen.contains(resultat))
      {
                System.out.println("Inloggad");
                new AlienInformation().setVisible(rootPaneCheckingEnabled);
    }                                               
        
      else 
        {
        JOptionPane.showMessageDialog(null, "Kunde inte logga in, kontrollera dina upppgifter");
        }
    }
      
    catch(InfException ettUndantag) {
              JOptionPane.showMessageDialog(null, "Något gick fel!");
              System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    }
    
        
        
        
        
      
    }//GEN-LAST:event_btnAlienLoggaInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlienInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlienInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlienInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlienInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlienInlogg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlienLoggaIn;
    private javax.swing.JLabel jlAlienID;
    private javax.swing.JLabel jlAlienInloggning;
    private javax.swing.JLabel jlLosenord;
    private javax.swing.JTextField tfAngivetAlienID;
    private javax.swing.JTextField tfAngivetAlienLosenord;
    // End of variables declaration//GEN-END:variables
}
